services:
  web:
    build: ./php
    container_name: sqli-web
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: sqli-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sqli_project
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db-data: